cmake_minimum_required(VERSION 3.22)
project(mt4g LANGUAGES CXX)

find_package(HIP REQUIRED)

if(DEFINED NVIDIA_UARCH)
    string(TOUPPER "${NVIDIA_UARCH}" NVIDIA_UARCH)
endif()

if(DEFINED AMD_UARCH)
    string(TOUPPER "${AMD_UARCH}" AMD_UARCH)
endif()

set(COMPUTE_CAP_COMPILE_OPTIONS "")

if(HIP_PLATFORM STREQUAL "nvidia")
    message(STATUS "Configuring for HIP on NVIDIA...")

    if(NVIDIA_UARCH STREQUAL "KEPLER")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:-gencode=arch=compute_35,code=sm_35>")
    elseif(NVIDIA_UARCH STREQUAL "MAXWELL")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:-gencode=arch=compute_50,code=sm_50>")
    elseif(NVIDIA_UARCH STREQUAL "PASCAL")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:-gencode=arch=compute_60,code=sm_60>")
    elseif(NVIDIA_UARCH STREQUAL "VOLTA")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:-gencode=arch=compute_70,code=sm_70>")
    elseif(NVIDIA_UARCH STREQUAL "TURING")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:-gencode=arch=compute_75,code=sm_75>")
    elseif(NVIDIA_UARCH STREQUAL "AMPERE")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:-gencode=arch=compute_86,code=sm_86>")
    elseif(NVIDIA_UARCH STREQUAL "HOPPER")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:-gencode=arch=compute_90,code=sm_90>")
    else()
        message(STATUS "No (or unknown) NVIDIA_UARCH specified. Using default HIP/nvcc arch.")
    endif()

elseif(HIP_PLATFORM STREQUAL "amd")
    message(STATUS "Configuring for HIP on AMD...")
    if(AMD_UARCH STREQUAL "VEGA20")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:--amdgpu-target=gfx906>")
    elseif(AMD_UARCH STREQUAL "ARCTURUS")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:--amdgpu-target=gfx908>")
    elseif(AMD_UARCH STREQUAL "ALDEBARAN")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:--amdgpu-target=gfx90a>")
    elseif(AMD_UARCH STREQUAL "NAVI21")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:--amdgpu-target=gfx1030>")
    elseif(AMD_UARCH STREQUAL "RDNA3")
        set(COMPUTE_CAP_COMPILE_OPTIONS "PRIVATE" "$<$<COMPILE_LANGUAGE:HIP>:--amdgpu-target=gfx1100>")
    else()
        message(STATUS "No (or unknown) AMD_UARCH specified. Using default HIP/clang arch.")
    endif()

else()
    message(WARNING "HIP_PLATFORM neither 'nvidia' nor 'amd'! Defaulting to HIP's compiler settings.")
endif()

set(COMPUTE_CAP_COMPILE_OPTIONS ${COMPUTE_CAP_COMPILE_OPTIONS} CACHE STRING "Arch-specific compile options" FORCE)

add_subdirectory(src)
